### ISSUE TITLE
Error importing file .tar.gz  to replace a course content in studio

### ISSUE THREAD

**Issue by abstract-technology** [Abstract-Tech/derex.runner#10]
Trying to import a  .tar.gz file to replace a course content in STUDIO by TOOLS >> IMPORT is not possible. The system start to upload the file transferring it to the servers. But the status is not changing to the next step which should be Unpacking >> Verifying >> Updating Course >> Success

**Comment by silviot** [comment]
Fixed with the updated celery workers config.
