### ISSUE TITLE
Fix COMPREHENSIVE_THEMES_DIR

### ISSUE THREAD

**Issue by laithmassoud** [Abstract-Tech/derex.runner#62]
This line should be removed: https://github.com/Abstract-Tech/derex.runner/blob/4eacb947ff5ec2767dcf1f05b62235582ee598e8/derex/runner/settings/derex/base.py#L135

this one is enough: https://github.com/Abstract-Tech/derex.runner/blob/4eacb947ff5ec2767dcf1f05b62235582ee598e8/derex/runner/settings/derex/base.py#L150

**Comment by silviot** [comment]
This was fixed in #85
